Get involved page 3  roadmap/ memorandum  UI
orcasound/orcahome pull request #114
Opened 2023-04-28 20:24 UTC by NayoBaez

**Get Involved Page**
_Assigned issues:  #48 & #108_  
- Added all included links to text & buttons 
- Double checked all instances of "Orcasound" 
- Provided controls to allow user to zoom in / out / reset image
- Made responsive to desktop / tablet & mobile as in [Figma Design](https://www.figma.com/file/YdvbAjHETokV2x1LBHaElj/Orcahome-%2F-Orcasound-Website-Redesign-2021?type=design&node-id=860-2526&t=qGFRynj9BuoKUioI-0#409937693)

2023-05-26 21:18 UTC, JacobYLiu commented
@evanjscallan We finished fixing the checks on this pull request as well.

2023-06-01 16:43 UTC, evanjscallan commented on package.json
> +    "next": "^12.3.4",
Not sure if the next version should change here.

2023-06-01 16:46 UTC, evanjscallan commented on src/pages/getinvolved.jsx
> +            fontSize="16px"
seeing fontSize of 16px and 20px which are fairly similar. Not sure if intention

2023-06-01 16:47 UTC, evanjscallan commented on src/pages/getinvolved.jsx
> +          If you are an individual wanting to volunteer , collaborate or donate,
comma spacing

2023-06-01 16:48 UTC, evanjscallan commented on src/pages/getinvolved.jsx
> +          {''} to begin collaborating. There are no membership fees-- just
spacing

2023-06-01 16:51 UTC, evanjscallan commented on package.json
> +    "next-image-zoom": "^1.1.7",
where is this being used?

2023-06-01 16:53 UTC, evanjscallan requested changes
See comments

2023-06-06 15:22 UTC, NayoBaez commented on src/pages/getinvolved.jsx
> +          If you are an individual wanting to volunteer , collaborate or donate,
Fixed, thank you!

2023-06-06 15:27 UTC, NayoBaez commented on src/pages/getinvolved.jsx
> +          {''} to begin collaborating. There are no membership fees-- just
Fixed, thank you!

2023-06-06 15:56 UTC, NayoBaez commented
@evanjscallan Hi Evan, how are you? Just wanted your guidance, i fixed all the review changes but now my checks won't pass. It's asking me to update the typescript version and also reinstall the latest Netlify plugin version. If i update they won't match with the original versions. What would you recommend?

2023-09-18 20:47 UTC, UXBrendan commented
@UXBrendan 

Deploy preview passes UI check. 😎

2023-10-17 18:16 UTC, scottveirs approved these changes
Thanks for responding to Evan's feedback. Looks good to the oceanographer!

2023-10-17 18:22 UTC, merged