migrate from bootstrap to MUIv5
orcasound/orcahome pull request #40
Opened 2022-02-01 10:02 UTC by DivyanshuParwal

#11 resolved

2022-02-02 04:42 UTC, paulcretu requested changes
Thanks for doing the refactor! Just a few comments

2022-02-02 04:42 UTC, paulcretu commented on src/pages/about.jsx
> +        <Card sx={{ maxWidth: 345, marginBottom: '20px' }}>
```suggestion
        <Card sx={{ maxWidth: 345, mb: 2 }}>
```

Ideally use the [MUI spacing](https://mui.com/system/spacing/) utility when possible. Default unit is 8px so `mb: 2` = 16px

2022-02-02 04:42 UTC, paulcretu commented on src/pages/about.jsx
> +            <Typography gutterBottom variant="h5" component="div">
```suggestion
            <Typography gutterBottom variant="h5">
```

Does it need to be a div? What's wrong with `h5`?

2022-02-02 04:42 UTC, paulcretu commented on src/pages/getinvolved.jsx
> -            </Card>
Looks like you're missing this card in the new version

2022-02-02 04:42 UTC, paulcretu commented on src/pages/about.jsx
> +            height="140"
If you're going to constantly be re-using a card with the same props (`component` and `height`) maybe it's worth making it into a new component or use `styled()`

2022-02-02 05:52 UTC, DivyanshuParwal commented
Thanks @paulcretu for your comments. What I was thinking when working on this issue was to just remove bootstrap components with temp components which will ultimately be removed by the components according to the designs. So should I work on suggestions like creating a new reusable card component and creating a card for the missed one which I think is an unnecessary work ?

2022-02-02 05:53 UTC, DivyanshuParwal commented on package.json
> +    "@types/node": "^17.0.13",
I’ll remove this

2022-02-03 03:46 UTC, paulcretu commented
@DivyanshuParwal yeah that's a good point. I actually didn't mean to request changes for all the suggestions, just for removing `@types/node`. My mistake, I should have been more clear. All the other comments are feedback in case you find it helpful—they're not blocking. So go ahead and remove `package.json`/`package-lock.json` and I'll merge

2022-02-03 08:31 UTC, DivyanshuParwal commented
@paulcretu I have removed @types/node

2022-02-06 00:33 UTC, paulcretu commented
@DivyanshuParwal `package-lock.json` is still conflicting, you may want to rebase/merge changes from `main` into your branch

2022-02-06 13:33 UTC, DivyanshuParwal commented
@paulcretu merge conflict resolved.

2022-02-07 06:29 UTC, paulcretu approved these changes

2022-02-07 06:32 UTC, merged